const _ = require('lodash')
const x = {
    "07/06/2020": [
        {
            "idClient": 1,
            "clientName": "Luiz Henrique",
            "rateAVG": 0,
            "geoLocX": -19.8483,
            "geoLocY": -43.9145,
            "zipCode": 31980430,
            "number": 66,
            "street": "R. Canto do Buriti",
            "complement": "CASA",
            "neighborhood": "São Gabriel",
            "city": "Belo Horizonte",
            "state": "MG",
            "typeSchedulingId": 3,
            "nametypeSchedulig": "Bug",
            "statusSchedulingId": 1,
            "nameStatusScheduling": "Aguardando Aceite",
            "schedulingId": 7,
            "dateTime": "2020-06-07 10:00:00",
            "observation": "você?",
            "createdAt": "2020-05-21 15:34:13",
            "distance": 10374,
            "isInRangeDistance": true,
            "date": "07/06/2020"
        },
        {
            "idClient": 2,
            "clientName": "Maria da silva",
            "rateAVG": 0,
            "geoLocX": -19.8467,
            "geoLocY": -43.9059,
            "zipCode": 31870150,
            "number": 354,
            "street": "Rua papa honorio III",
            "complement": "CASA",
            "neighborhood": "Ouro Minas",
            "city": "Belo Horizonte",
            "state": "MG",
            "typeSchedulingId": 3,
            "nametypeSchedulig": "Bug",
            "statusSchedulingId": 1,
            "nameStatusScheduling": "Aguardando Aceite",
            "schedulingId": 8,
            "dateTime": "2020-06-07 10:00:00",
            "observation": "to",
            "createdAt": "2020-05-21 15:34:13",
            "distance": 11823,
            "isInRangeDistance": true,
            "date": "07/06/2020"
        },
        {
            "idClient": 3,
            "clientName": "Josefina das dores",
            "rateAVG": 0,
            "geoLocX": -22.9129,
            "geoLocY": -43.1856,
            "zipCode": 20231091,
            "number": 88,
            "street": "R. do Rezende",
            "complement": "CASA",
            "neighborhood": "Centro",
            "city": "Rio de Janeiro",
            "state": "RJ",
            "typeSchedulingId": 3,
            "nametypeSchedulig": "Bug",
            "statusSchedulingId": 1,
            "nameStatusScheduling": "Aguardando Aceite",
            "schedulingId": 9,
            "dateTime": "2020-06-07 10:00:00",
            "observation": "bem <3",
            "createdAt": "2020-05-21 15:34:13",
            "distance": 439452,
            "isInRangeDistance": true,
            "date": "07/06/2020"
        }
    ],
    "03/06/2020": [
        {
            "idClient": 1,
            "clientName": "Luiz Henrique",
            "rateAVG": 0,
            "geoLocX": -19.8483,
            "geoLocY": -43.9145,
            "zipCode": 31980430,
            "number": 66,
            "street": "R. Canto do Buriti",
            "complement": "CASA",
            "neighborhood": "São Gabriel",
            "city": "Belo Horizonte",
            "state": "MG",
            "typeSchedulingId": 2,
            "nametypeSchedulig": "Instalação",
            "statusSchedulingId": 1,
            "nameStatusScheduling": "Aguardando Aceite",
            "schedulingId": 4,
            "dateTime": "2020-06-03 10:00:00",
            "observation": "sim",
            "createdAt": "2020-05-21 15:34:13",
            "distance": 10374,
            "isInRangeDistance": true,
            "date": "03/06/2020"
        },
        {
            "idClient": 3,
            "clientName": "Josefina das dores",
            "rateAVG": 0,
            "geoLocX": -22.9129,
            "geoLocY": -43.1856,
            "zipCode": 20231091,
            "number": 88,
            "street": "R. do Rezende",
            "complement": "CASA",
            "neighborhood": "Centro",
            "city": "Rio de Janeiro",
            "state": "RJ",
            "typeSchedulingId": 1,
            "nametypeSchedulig": "Manutenção",
            "statusSchedulingId": 1,
            "nameStatusScheduling": "Aguardando Aceite",
            "schedulingId": 3,
            "dateTime": "2020-06-03 10:00:00",
            "observation": "bem?",
            "createdAt": "2020-05-21 15:34:13",
            "distance": 439452,
            "isInRangeDistance": true,
            "date": "03/06/2020"
        }
    ],
    "01/06/2020": [
        {
            "idClient": 1,
            "clientName": "Luiz Henrique",
            "rateAVG": 0,
            "geoLocX": -19.8483,
            "geoLocY": -43.9145,
            "zipCode": 31980430,
            "number": 66,
            "street": "R. Canto do Buriti",
            "complement": "CASA",
            "neighborhood": "São Gabriel",
            "city": "Belo Horizonte",
            "state": "MG",
            "typeSchedulingId": 1,
            "nametypeSchedulig": "Manutenção",
            "statusSchedulingId": 5,
            "nameStatusScheduling": "Terminado",
            "schedulingId": 1,
            "dateTime": "2020-06-01 10:00:00",
            "observation": "oi",
            "createdAt": "2020-05-21 15:34:13",
            "distance": 10374,
            "isInRangeDistance": true,
            "date": "01/06/2020"
        },
        {
            "idClient": 2,
            "clientName": "Maria da silva",
            "rateAVG": 0,
            "geoLocX": -19.8467,
            "geoLocY": -43.9059,
            "zipCode": 31870150,
            "number": 354,
            "street": "Rua papa honorio III",
            "complement": "CASA",
            "neighborhood": "Ouro Minas",
            "city": "Belo Horizonte",
            "state": "MG",
            "typeSchedulingId": 1,
            "nametypeSchedulig": "Manutenção",
            "statusSchedulingId": 1,
            "nameStatusScheduling": "Aguardando Aceite",
            "schedulingId": 2,
            "dateTime": "2020-06-01 10:00:00",
            "observation": "tudo",
            "createdAt": "2020-05-21 15:34:13",
            "distance": 11823,
            "isInRangeDistance": true,
            "date": "01/06/2020"
        }
    ],
    "05/06/2020": [
        {
            "idClient": 2,
            "clientName": "Maria da silva",
            "rateAVG": 0,
            "geoLocX": -19.8467,
            "geoLocY": -43.9059,
            "zipCode": 31870150,
            "number": 354,
            "street": "Rua papa honorio III",
            "complement": "CASA",
            "neighborhood": "Ouro Minas",
            "city": "Belo Horizonte",
            "state": "MG",
            "typeSchedulingId": 2,
            "nametypeSchedulig": "Instalação",
            "statusSchedulingId": 1,
            "nameStatusScheduling": "Aguardando Aceite",
            "schedulingId": 5,
            "dateTime": "2020-06-05 10:00:00",
            "observation": "e",
            "createdAt": "2020-05-21 15:34:13",
            "distance": 11823,
            "isInRangeDistance": true,
            "date": "05/06/2020"
        },
        {
            "idClient": 3,
            "clientName": "Josefina das dores",
            "rateAVG": 0,
            "geoLocX": -22.9129,
            "geoLocY": -43.1856,
            "zipCode": 20231091,
            "number": 88,
            "street": "R. do Rezende",
            "complement": "CASA",
            "neighborhood": "Centro",
            "city": "Rio de Janeiro",
            "state": "RJ",
            "typeSchedulingId": 2,
            "nametypeSchedulig": "Instalação",
            "statusSchedulingId": 1,
            "nameStatusScheduling": "Aguardando Aceite",
            "schedulingId": 6,
            "dateTime": "2020-06-05 10:00:00",
            "observation": "com",
            "createdAt": "2020-05-21 15:34:13",
            "distance": 439452,
            "isInRangeDistance": true,
            "date": "05/06/2020"
        }
    ]
}

_.reverse(x)
console.log(x)